# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/fiddler-core"

# Exclude files which should not be in the output
exclude: [README.md, Gemfile, Gemfile.lock]
exclude_navigation: ["knowledge-base/*"]

## List your directory names and order here, like this:
navigation:
    getting-started:
        title: Getting Started
        position: 1

    basic-usage:
        title: Basic Usage
        position: 2
    
    knowledge-base:
        title: Knowledge Base
        position: 21
    
    licensing: 
        title: Licensing
        position: 1101

## Product title
product: "Progress Telerik FiddlerCore"
platform: fiddler-core

## An experimental property to resolve the SEO vs STA panels conflicts discussed in the following issue: https://github.com/telerik/docs-seed/issues/159
## Use only with docs-seed branch #fiddler-page-title
page_title_product: "FiddlerCore"
use_product_in_title: true


## The application virtual path
baseurl: /fiddler-core

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "fiddler-core"
        editable: true

has_kb_portal: true
has_api_reference: true

# Feedback Form ID
ff-sheet-id: 2753d516-bb0c-85f5-3898-3620db972174

# The google services configuration
google_analytics: UA-111455-1
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:bhf815yqanw'
gcs_api_key: 'AIzaSyDWHnF6UKhvS44zCVYggJysw98qCaInqiE'

edit_repo_url: https://github.com/telerik/fiddler-core-docs/edit/master

footer:
-
  title: "Getting Started"
  links:
    "Try Now": https://www.telerik.com/download/fiddler-core
-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/fiddler
    "Blogs": https://www.telerik.com/blogs/tag/fiddler
    "Feedback Portal": https://feedback.telerik.com/fiddler-core
  
footer_social: 
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/ 
    twitter: https://twitter.com/TelerikFiddler/ 

api_reference_url: "api/"

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
